### ISSUE TITLE
angr.analyses.vfg results in an uninitialized access (used as addr)

### ISSUE THREAD

**Issue by hira-a** [angr/angr-dev#1]
related python test code :

```
    # __main__

   binary = angr.Project(target_binary_path, 
                         load_options={"auto_load_libs": False})
    analyze(binary)

   #  analyze (binary)

    cfg = binary.analyses.CFG(context_sensitivity_level=3, keep_state=True)    
    vfg = binary.analyses.VFG(cfg, interfunction_level=150)
    vfg_ddg = binary.analyses.VSA_DDG(vfg, context_sensitivity_level=3, keep_data=True)
```

Here is the stack trace (target binary is attached):

```
ERROR   | 2016-02-26 00:13:24,853 | angr.analyses.vfg | Found an uninitialized access (used as addr) at expression <BV64 Reverse(global_7ffffffffff0010_51_64)>.
ERROR   | 2016-02-26 00:13:24,854 | angr.analyses.vfg | Variable global_7ffffffffff0010_51_64 does not exist in self._uninitialized_access. Please report it to Fish.
Traceback (most recent call last):
  File "analyze.py", line 88, in <module>
    analyze(binary)
  File "analyze.py", line 63, in analyze
    vfg = binary.analyses.VFG(cfg, interfunction_level=150)
  File "/home/osboxes/angr-dev/angr/angr/analysis.py", line 84, in make_analysis
    oself.__init__(*args, **kwargs)
  File "/home/osboxes/angr-dev/angr/angr/analyses/vfg.py", line 130, in __init__
    self._construct(initial_state=initial_state)
  File "/home/osboxes/angr-dev/angr/angr/analyses/vfg.py", line 254, in _construct
    self._ai_analyze(initial_state)
  File "/home/osboxes/angr-dev/angr/angr/analyses/vfg.py", line 320, in _ai_analyze
    tracing_times, retn_target_sources
  File "/home/osboxes/angr-dev/angr/angr/analyses/vfg.py", line 436, in _handle_entry
    simrun, error_occured, restart_analysis = self._get_simrun(input_state, current_path, addr)
  File "/home/osboxes/angr-dev/angr/angr/analyses/vfg.py", line 982, in _get_simrun
    sim_run = self.project.factory.sim_run(current_path.state, jumpkind=jumpkind)
  File "/home/osboxes/angr-dev/angr/angr/factory.py", line 114, in sim_run
    r = sim_proc_class(state, addr=addr, sim_kwargs=kwargs)
  File "/home/osboxes/angr-dev/simuvex/simuvex/s_procedure.py", line 62, in __init__
    r = run_func(*args, **self.kwargs)
  File "/home/osboxes/angr-dev/simuvex/simuvex/procedures/libc___so___6/fopen.py", line 32, in run
    p_strlen = strlen(self.state, inline=True, arguments=[p_addr])
  File "/home/osboxes/angr-dev/simuvex/simuvex/s_procedure.py", line 62, in __init__
    r = run_func(*args, **self.kwargs)
  File "/home/osboxes/angr-dev/simuvex/simuvex/procedures/libc___so___6/strlen.py", line 32, in run
    self.max_null_index = max(self.max_null_index + i)
TypeError: unsupported operand type(s) for +: 'int' and 'list'
```

[wordcount.tar.gz](https://github.com/angr/angr-dev/files/147496/wordcount.tar.gz)

**Comment by ltfish** [comment]
Reformatted your comment to make it look better :-)

We are aware of this issue. It was fixed some time ago, and apparently this is a regression. I'll make sure to fix it in the next release.

**Comment by ltfish** [comment]
Also, please submit any angr-related issue to https://github.com/angr/angr instead.
