### ISSUE TITLE
No tracer repo inside setup.sh

### ISSUE THREAD

**Issue by amttr** [angr/angr-dev#27]
Maybe not an issue, but one of the tests inside **angr** doesnt work without a **tracer**

```bash
======================================================================
ERROR: Test identification of common comparison functions
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/home/amatter/.virtualenvs/angr.io/local/lib/python2.7/site-packages/nose/case.py", line 197, in runTest
    self.test(*self.arg)
  File "/home/amatter/angr-dev/angr/tests/test_identifier.py", line 18, in test_comparison_identification
    idfer = p.analyses.Identifier(require_predecessors=False)
  File "/home/amatter/angr-dev/angr/angr/analysis.py", line 99, in make_analysis
    oself.__init__(*args, **kwargs)
  File "/home/amatter/angr-dev/angr/angr/analyses/identifier/identify.py", line 53, in __init__
    self._runner = Runner(self.project, self._cfg)
  File "/home/amatter/angr-dev/angr/angr/analyses/identifier/runner.py", line 28, in __init__
    from tracer.simprocedures import FixedOutTransmit, FixedInReceive
ImportError: No module named tracer.simprocedures
```

**Comment by rhelmot** [comment]
Tracer is required for this test, but it's totally unreasonable to expect the user to have it installed - it involves installing several copies of specially-built qemu. The correct fix is to make nose skip this test if we detect that tracer is not installed.

**Comment by rhelmot** [comment]
https://github.com/angr/angr/blob/f82cf89fbae26eefd46b34f22ba086e21729832a/tests/test_signed_div.py here is an example of how to make nose skip a test under a certain condition, in this case if we're running under an operating system besides Linux.

**Comment by rhelmot** [comment]
this has been fixed on our current development branch, `wip/the_end_times` on angr: e0c934c

Expect it to get merged to master... sometime in the next week probably?
