### ISSUE TITLE
"libvex failed to initialize" error when import angr

### ISSUE THREAD

**Issue by DongShuaike** [angr/angr-dev#96]
Hi, the error occurs when I just `git_all.sh pull` the latest angr-dev branch.

The detailed error info is as below:
```
>>> import angr
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/home/dsk/Tools/Labs/angr-dev/angr/angr/__init__.py", line 30, in <module>
    from .sim_procedure import SimProcedure
  File "/home/dsk/Tools/Labs/angr-dev/angr/angr/sim_procedure.py", line 5, in <module>
    from cle import SymbolType
  File "/home/dsk/Tools/Labs/angr-dev/cle/cle/__init__.py", line 18, in <module>
    from .loader import *
  File "/home/dsk/Tools/Labs/angr-dev/cle/cle/loader.py", line 1099, in <module>
    from .backends import MetaELF, ELF, PE, Soot, Blob, ALL_BACKENDS, Backend
  File "/home/dsk/Tools/Labs/angr-dev/cle/cle/backends/__init__.py", line 415, in <module>
    from .elf import ELF, ELFCore, MetaELF
  File "/home/dsk/Tools/Labs/angr-dev/cle/cle/backends/elf/__init__.py", line 1, in <module>
    from .elf import ELF
  File "/home/dsk/Tools/Labs/angr-dev/cle/cle/backends/elf/elf.py", line 15, in <module>
    from .metaelf import MetaELF, maybedecode
  File "/home/dsk/Tools/Labs/angr-dev/cle/cle/backends/elf/metaelf.py", line 1, in <module>
    import pyvex
  File "/home/dsk/Tools/Labs/angr-dev/pyvex/pyvex/__init__.py", line 44, in <module>
    pvc = _find_c_lib() # type: Any # This should be properly typed, but this seems non trivial
  File "/home/dsk/Tools/Labs/angr-dev/pyvex/pyvex/__init__.py", line 39, in _find_c_lib
    raise ImportError("libvex failed to initialize")
ImportError: libvex failed to initialize
```

**Comment by DongShuaike** [comment]
I tried to solve this by following commands
```
workon angr-dev
pip uinstall pyvex cle angr angrop angr-management
pip install pyvex cle angr angrop angr-management
```
It seems using pip, version 8.20.1.7 of the suit is installed and the error comes from previous 8.19.17 version.
